# Generated by Django 5.1.3 on 2024-12-09 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('factory_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2024)])),
                ('model_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
