# Generated by Django 5.1.3 on 2025-02-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_bio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carinventory',
            table='Car_Inventory',
        ),
    ]
