# Generated by Django 5.1.3 on 2025-02-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carinventory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carinventory',
            table='car_inventory',
        ),
    ]
