# Generated by Django 5.1.3 on 2025-02-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carinventory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bio',
            new_name='description',
        ),
    ]
