# Generated by Django 5.1.3 on 2025-02-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_bio_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='media/cars/no_photo.jpg', null=True, upload_to='cars/'),
        ),
    ]
